### ISSUE TITLE
Error reporting with source

### ISSUE THREAD

**Issue by AppShipIt** [pjeby/regenerator-loader#10]
Regenerator doesn't report file context. Locally I modified the loader to print source with line numbers. Would you be interested in a PR?

```js
try {
    var result = regenerator.compile(source);
} catch (e) {
    console.log('Error in [regenerator] ' + e.message);
    console.log(source
        .split(/^/gm)
        .map(function (line, index) {
            var num = index + 1 + '';
            var indent = '    '.slice(num.length);
            return indent + num + ': ' + line;
        })
        .filter(function (line, index) {
            return !(Math.abs(index + 1 - e.lineNumber) > 2);
        })
        .join('')
    );
    throw e;
}
```

**Comment by pjeby** [comment]
I think this belongs upstream, since it's a regenerator issue, not an issue with the loader.  Thanks for asking, though.

**Comment by AppShipIt** [comment]
Thanks I'll report it there 👍

**Comment by texastoland** [comment]
No reply but I feel like it might be better here since their job is surfacing errors in API not necessarily for presentation?
