### ISSUE TITLE
bump dependency regenerator-runtime to 0.10.0

### ISSUE THREAD

**Issue by charlierudolph** [pjeby/regenerator-loader#11]

**Comment by pjeby** [comment]
I'm currently out of town and away from my development machine; if you'd like to submit a PR I could merge it, though.  Needs to still support the older runtime, though.

**Comment by pjeby** [comment]
So, looking at what's going on upstream, it's not clear to me whether it's a simple matter of updating package.json for the dependency.  If you can confirm that a modified dependency works, I'll make the change.  Otherwise, I'm going to have to close this issue.

**Comment by charlierudolph** [comment]
On one of my projects, I had updated regenerator runtime to 0.10.0 and used this version of regenerator loader and things worked for me. 

I opened an issue on regenerator for them to add a changelog so that hopefully its easier to tell in the future.

Feel free to close.

**Comment by pjeby** [comment]
Updated and published as regenerator-loader 3.1.0
