### ISSUE TITLE
Regenerator v0.8.1 now tells you if changes were made

### ISSUE THREAD

**Issue by dashed** [pjeby/regenerator-loader#2]
See:
https://github.com/facebook/regenerator/blob/e8ffd35f761bc3d7ce6b9e0f83edbc5b71d63602/lib/visit.js#L38
https://github.com/facebook/regenerator/issues/152
https://github.com/facebook/regenerator/commit/0f71256996cce65b0beee3a51262e2f32c1ba724

This would be better than naive regex.

**Comment by benmosher** [comment]
At that point you've already executed the parse, though.

I assumed the regex is there to prevent the (probably more expensive) parse in the likely case that the file contains no generators.

**Comment by pjeby** [comment]
Yep.  ;-)  Also, there is at this point still no official notice of the change, just the option to optionally inject the runtime.  So we still have to do this the way we're doing this.
