### ISSUE TITLE
generator not compiled when webpack with babel-loader

### ISSUE THREAD

**Issue by wangst321** [pjeby/regenerator-loader#5]
webpack.js::

    loaders: [{ test: /\.js$/, loader: 'babel',}]

app.js::

    require('regenerator!./generator.js');

generator.js::

    function * range(start, end) {
        for (let i=start; i<end; i++) {
            yield i;
        }
    }
    
    for (let i of range(1, 10)) {
        console.log(i);
    }

Run the compilation with::

    $ webpack -o bundle.js app.js

Until now, everything is ok. But when running ``bundle.js`` in firefox::

    regeneratorRuntime is not defined

So, after a few try and google, i guess maybe the ``loader`` does not work. I edit ``regenerator-loader/index.js`` , logging the source before the compile test. I found the following interesting:

    var marked0$0 = [range].map(regeneratorRuntime.mark);
    function range(start, end) {
        var i;
        return regeneratorRuntime.wrap(function range$(context$1$0) {
            while (1) switch (context$1$0.prev = context$1$0.next) {
    ...

it seems ``babel-loader`` has already compile the souce with  ``regeneratorRuntime.mark``, as a result ``regenerator-loader`` will not compile it because it fail to find ``function * `` or `` async function`` , and ``runtime`` is not added.

**Comment by pjeby** [comment]
If you're using babel-loader, why are you also using regenerator-loader?  Babel needs the Babel-specific polyfill, not the generic regeneratorRuntime.  So don't use regenerator-loader with Babel: import the babel-core/polyfill instead, as described in [this babel-loader issue](https://github.com/babel/babel-loader/issues/92).
