### ISSUE TITLE
Document how to set a project-wide postloader

### ISSUE THREAD

**Issue by shimaore** [pjeby/regenerator-loader#8]
The documentation currently says

    The simplest method of all [...] is just to specify it as a post-loader for your entire project[...].

but I'm having a hard time finding documentation on how to do that. (I'll grant you I'm a webpack newbie.) I can see how to define a postloader for a specific file, but not the entire project.

**Comment by pjeby** [comment]
If I recall correctly, you should be able to just define a postloader `*.js`.  You might try that, in any case.

**Comment by hpurmann** [comment]
In case you might still have problems, such a postloader for Javascript files looks like this:
```javascript
{
  test: /\.js/,
  loaders: ['regenerator-loader']
}
```
