### ISSUE TITLE
The regenerator/runtime module is deprecated

### ISSUE THREAD

**Issue by AppShipIt** [pjeby/regenerator-loader#9]
See https://github.com/facebook/regenerator/commit/18df917126ab854ace16ded77af4164c9b315ea2.

**Comment by pjeby** [comment]
I've checked in changes for this; please try using the current master head version and let me know if it works for you.

**Comment by AppShipIt** [comment]
LGTM!

**Comment by pjeby** [comment]
Um, by LGTM do you mean it literally looks good, or have you actually *tried* it?  ;-)

**Comment by AppShipIt** [comment]
Haha I plan to plug it in late tonight but the diff looks straightforward too 😄

**Comment by pjeby** [comment]
Let me know when you've actually tested it.  Thanks.

**Comment by AppShipIt** [comment]
Confirmed in my TypeScript build at work.

**Comment by AppShipIt** [comment]
Okay Regenerator depends on the runtime so works as advertised 👍 It might be worth noting no additional dependency is necessary.

**Comment by pjeby** [comment]
The additional dependency is still necessary if you're working with npm2.  But thanks for reporting your results!  I've gone ahead and updated the npm version.
